-- BookMyTicket schema (Neon / PostgreSQL). The "bmt_local" schema is created by Flyway
-- (spring.flyway.create-schemas=true, default-schema=bmt_local) so the app owns its own
-- namespace and never collides with other schemas in the same database. Hibernate
-- runs in validate mode, so these columns must match the JPA entities exactly.

CREATE TABLE bmt_local.movies (
    id            VARCHAR(255) PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    language      VARCHAR(255),
    genre         VARCHAR(255),
    duration_mins INTEGER,
    certificate   VARCHAR(255),
    rating        DOUBLE PRECISION,
    poster_url    VARCHAR(255)
);

CREATE TABLE bmt_local.theatres (
    id   VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255)
);

CREATE TABLE bmt_local.shows (
    id          VARCHAR(255) PRIMARY KEY,
    movie_id    VARCHAR(255) REFERENCES bmt_local.movies(id),
    theatre_id  VARCHAR(255) REFERENCES bmt_local.theatres(id),
    screen_name VARCHAR(255),
    start_time  TIMESTAMP(6)
);

-- the concurrency-critical table: one row per seat per show, with a version column
CREATE TABLE bmt_local.show_seats (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id    VARCHAR(255) NOT NULL REFERENCES bmt_local.shows(id),
    seat_label VARCHAR(255) NOT NULL,
    row_idx    INTEGER,
    col_idx    INTEGER,
    seat_type  VARCHAR(255),
    status     VARCHAR(255),
    held_by    VARCHAR(255),
    held_until TIMESTAMP(6) WITH TIME ZONE,
    version    BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_show_seat UNIQUE (show_id, seat_label)
);

CREATE TABLE bmt_local.users (
    id    VARCHAR(255) PRIMARY KEY,
    name  VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255)
);

CREATE TABLE bmt_local.bookings (
    id           VARCHAR(255) PRIMARY KEY,
    user_id      VARCHAR(255),
    show_id      VARCHAR(255),
    status       VARCHAR(255),
    total_amount DOUBLE PRECISION,
    seats        VARCHAR(255),
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    version      BIGINT NOT NULL DEFAULT 0
);
